# Generated by Django 4.2.1 on 2023-06-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='Pro_productImage',
            field=models.ImageField(upload_to='Image/'),
        ),
    ]
