# Generated by Django 4.2.1 on 2023-06-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_pro_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Pro_productImage',
            field=models.ImageField(default=1, upload_to='Image/'),
            preserve_default=False,
        ),
    ]
