# Generated by Django 4.2.1 on 2023-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_pro_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='Pro_productImage',
        ),
        migrations.AddField(
            model_name='productimage',
            name='Pro_productImagey',
            field=models.ImageField(default=1, upload_to='Image/'),
            preserve_default=False,
        ),
    ]
