# Generated by Django 4.2.1 on 2023-06-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productimage_pro_productimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Pro_product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
